name: PR Flow

on:
    push:
        branches: [feat/*, fix/*, custom/*, refactor/*]
    pull_request:
        branches: [develop, main, release/**]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: '2'

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: '1.3.11'

            - name: Cache node modules
              id: cache
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ hashFiles('**/bun.lock', '**/bun.lockb', '**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: bun install --frozen-lockfile

            - name: Get short hash
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Extract branch name
              id: branch_name
              shell: bash
              run: echo "deploy_branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT

            - name: Extract build configuration
              shell: bash
              id: build_ext
              run: |
                  if [[ ${{ github.ref_name }} == *"feat"* ]]
                  then
                      echo "type=feat" >> $GITHUB_OUTPUT
                  elif [[ ${{ github.ref_name }} == *"fix"* ]]
                  then
                      echo "type=fix" >> $GITHUB_OUTPUT
                  elif [[ ${{ github.ref_name }} == *"custom"* ]]
                  then
                      echo "type=custom" >> $GITHUB_OUTPUT
                  else
                      echo "type=pr" >> $GITHUB_OUTPUT
                  fi

        outputs:
            type: ${{ steps.build_ext.outputs.type }}
            deploy_branch: ${{ steps.branch_name.outputs.deploy_branch }}
            short_sha: ${{ steps.vars.outputs.sha_short }}

    test:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: '1.3.11'

            - name: Cache node modules
              id: cache
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ hashFiles('**/bun.lock', '**/bun.lockb', '**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: bun install --frozen-lockfile

            - name: Run unit tests
              run: bun test

    build:
        runs-on: ubuntu-latest
        needs: setup
        env:
            deploy_branch: ${{ needs.setup.outputs.deploy_branch }}
            short_sha: ${{ needs.setup.outputs.short_sha }}
            type: ${{ needs.setup.outputs.type }}
        steps:
            - uses: actions/checkout@v6

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: '1.3.11'

            - name: Cache node modules
              id: cache
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ hashFiles('**/bun.lock', '**/bun.lockb', '**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: bun install --frozen-lockfile

            - name: Initialise Pipeline Chat Status
              uses: fjogeleit/http-request-action@master
              continue-on-error: true
              with:
                  url: ${{ secrets.STATUS_URL }}
                  data: '{ "chat_url": "${{ secrets.CHAT_URL }}", "name": "${{ github.repository }}", "commit": "${{ github.sha }}", "pipeline_name": "signage-wayfinder", "branch": "${{ github.ref }}", "status": "processing", "url": "https://github.com/${{ github.repository }}/runs/${{ github.run_id }}" }'

            - name: Build application
              run: bunx ng build --configuration=production

            - name: Deploy the application
              if: github.event_name == 'push'
              uses: MrYuion/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: build/${{ env.deploy_branch }}/signage-wayfinder
                  FOLDER: dist/signage-wayfinder/browser
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'build(signage-wayfinder): ${{ env.type }}[${{ env.deploy_branch }}] CI build from {sha}'

            - name: Update Pipeline Chat Status
              uses: fjogeleit/http-request-action@master
              continue-on-error: true
              with:
                  url: ${{ secrets.STATUS_URL }}
                  data: '{ "name": "${{ github.repository }}", "commit": "${{ github.sha }}", "pipeline_name": "signage-wayfinder", "branch": "${{ github.ref }}", "status": "${{ job.status }}", "url": "https://github.com/${{ github.repository }}/runs/${{ github.run_id }}" }'
              if: ${{ always() }}
